### ISSUE TITLE
到底怎么安装呢？安装不成功啊！

### ISSUE THREAD

**Issue by Dangjia** [slince/phpdish#1]
执行composer install命令后，最终出现这个错误：

  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException] 
  The path "fos_user.from_email.address" cannot contain an empty value, but got null.                                                                      
                                                                                

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception

  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:

    [Symfony\Component\Config\Definition\Exception\InvalidConfigurationExcept
  ion]
    The path "fos_user.from_email.address" cannot contain an empty value, but
   got null.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by slince** [comment]
原因很直接，缺少参数， 修改/app/config/paramter.yml 里面的 `mailer_user` 选项，随便填一个非空的值

ps: 有问题如果不能及时回复的话可以到 phpdish.com 发帖； 我看issue有时候不及时

**Comment by Dangjia** [comment]
谢谢，之前一直在config.yml里的from_email去修改。现在好了。但是安装完后还是有问题，详情见issue/2
