### ISSUE TITLE
不支持MySQL5.7吗？

### ISSUE THREAD

**Issue by LALADevil** [slince/phpdish#11]
无法创建管理员账号，提示：
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'charge' cannot be null

**Comment by slince** [comment]
是升级 还是全新安装的

**Comment by LALADevil** [comment]
全新安装的

**Comment by slince** [comment]
https://github.com/slince/phpdish/blob/master/src/PHPDish/Bundle/PostBundle/Entity/Category.php#L52 
改成 `protected $charge = 0;` 应该就好了

**Comment by LALADevil** [comment]
谢谢，已经好了。
