### ISSUE TITLE
error

### ISSUE THREAD

**Issue by alaikis** [slince/phpdish#14]
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".                                                                                                                      
remote:          Did you forget a "use" statement for another namespace? in /tmp/build_56a054c4917656f366c5652e3aa63a61/app/AppKernel.php:64

**Comment by slince** [comment]
具体点，是在做什么操作，贴个完整截图

**Comment by alaikis** [comment]
部署到heroku

**Comment by slince** [comment]
别用master里的代码，切换到tag里的代码；

```
composer install 
```
不要带上 `--no-dev`
