### ISSUE TITLE
安装成功后500错误

### ISSUE THREAD

**Issue by Dangjia** [slince/phpdish#2]
执行app_dev.php后出现：
PDOException  》PDOException 》 DriverException 》 Twig_Error_Runtime
HTTP 500 Internal Server Error
An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT DISTINCT id_5 FROM (SELECT t0_.title AS title_0, t0_.replied_at AS replied_at_1, t0_.reply_count AS reply_count_2, t0_.recommended AS recommended_3, t0_.stick_top AS stick_top_4, t0_.id AS id_5, t0_.body AS body_6, t0_.original_body AS original_body_7, t0_.comment_count AS comment_count_8, t0_.created_at AS created_at_9, t0_.updated_at AS updated_at_10, t0_.enabled AS enabled_11, t0_.vote_count AS vote_count_12 FROM topics t0_ WHERE t0_.enabled = ?) dctrn_result ORDER BY replied_at_1 DESC LIMIT 20 OFFSET 0' with params [1]:

SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.replied_at_1' which is not in SELECT list; this is incompatible with DISTINCT").

Twig_Error_Runtime
in src/PHPDish/Bundle/WebBundle/Resources/views/Topic/topic_list.html.twig (line 1)
**{% for topic in topics %}**    
<div class="media topic">        
    <div class="media-left">            
        <a href="{{ path('user_view', {'username': topic.user.username}) }}">                
          <img src="{{ asset(topic.user.avatar)|imagine_filter('middle_square') }}" class="media-object avatar" role="avatar">
             </a>

**Comment by slince** [comment]
设置下mysql，ps: 一般来说都是配置好的,如果出现了就按照这个方式改

### 方法一, 在mysql里执行
```
set global sql_mode = 0;
```

### 方法二写到mysql的配置文件里去

打开my.ini，加入
```
sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
```

**Comment by slince** [comment]
这是个通用的错误

**Comment by slince** [comment]
暂时关闭了，有问题可以再重启
