### ISSUE TITLE
更新 bootstrap 到 4.x

### ISSUE THREAD

**Issue by zoujiaqing** [slince/phpdish#20]
会不会升级 bootstrap ？毕竟 3.x 很久都不更新了。

**Comment by slince** [comment]
3.x 不更新是因为趋于文档，bootstrap4 和3 差异性还是比较大的，升级是个很麻烦的事情；升以后肯定会升但优先级不是最高的，有大招

**Comment by zoujiaqing** [comment]
不是稳定，是过时了，4.x 也已经稳定了，这个工作量的确大，可以放放哈哈哈
