### ISSUE TITLE
github登录问题

### ISSUE THREAD

**Issue by xulove** [slince/phpdish#21]
![image](https://user-images.githubusercontent.com/19432629/42919118-02c293ee-8b43-11e8-893d-b6e6ae65efb7.png)

想申请使用github登录，然后申请的时候需要填两个地址，这两个地址不会填。望指教。
安装文档中社交登录那块也已经看了，哪里没有提到这个啊

**Comment by slince** [comment]
homepage 随便填，就你那个域名； 授权回调看这里 


```
 在申请应用的时候，为了安全会需要你填写 redirect uri；三个平台的redirect uri 如下：

http://你的域名/check-github
http://你的域名/check-weibo
http://你的域名/check-qq
```
