### ISSUE TITLE
admin后台得静态资源构建

### ISSUE THREAD

**Issue by gouchaoer** [slince/phpdish#7]
![qq 20171206143536](https://user-images.githubusercontent.com/5207582/33647990-bc86e13e-da92-11e7-954a-bdf4e53339a5.png)

**Comment by slince** [comment]
这个在`composer install`的时候就会自动安装的，你这个不知道嘛原因丢了这个操作 

执行这个安装静态资源
```
$ php bin/console assets:install
```

**Comment by gouchaoer** [comment]
composer install的时候也没弹错误，手动执行之后ok了
